### ISSUE TITLE
How to define object key & values?

### ISSUE THREAD

**Issue by crobinson42** [grantila/suretype#11]
I can't seem to find a solution for typing `object`'s key=>value types, ie:

```
type Item = {
 [key: string]: StoreItem
}
```

Something like this would be a nice addition to the API:

```
import { v } from 'suretype'

const Item = v.objectKeyValue( v.string(), v.object({ ... }) )
```

**Comment by grantila** [comment]
@crobinson42 try an empty object (i.e. with no specific property defined) and use `additional`. The key being a string is implied.

```ts
v.object( )
    .additional( v.object( { ... } ) );
```

Please re-open if this didn't do it!

**Comment by crobinson42** [comment]
@grantila please re-open this issue - this error happens with your suggestion: `TypeError: Cannot convert undefined or null to object`

**Comment by crobinson42** [comment]
Disregard - it works with an empty object:

```
v.object( {} )
    .additional( v.object( { ... } ) );
 ```
