### ISSUE TITLE
Turn off colors in error explainations

### ISSUE THREAD

**Issue by domosapien** [grantila/suretype#13]
I'm trying to forward the error message onto a user, but since they don't support color codes, it comes out as gibberish. 

E.g.
```
"explaination":"[31m[1mThe [22m[39m[37m[3mroot object[23m[39m[31m[1m should not have the property [22m[39m[34m[3m ...
```

I see the underlying library `awesome-ajv-errors` has the ability to pass an option to turn on / off colors. Is there a way to pass this through?

**Comment by stuft2** [comment]
I want to suggest that it default to not using awesome-ajv-errors. An environment variable or argument should be used to turn in on.
