### ISSUE TITLE
uuid validation

### ISSUE THREAD

**Issue by dbartholomae** [grantila/suretype#18]
Hi, it seems the library currently does not support `'uuid'` as format, even though it is a valid string format [in the current standard](https://json-schema.org/draft/2020-12/json-schema-validation.html). I'm aware that this library tries to be minimal, so I wanted to ask whether there is interest in this addition before working on a PR.

**Comment by crobinson42** [comment]
A `'uuid'` is just a `string`, right?

**Comment by crobinson42** [comment]
#14

**Comment by dbartholomae** [comment]
Yes, this is a duplicate of #14
