### ISSUE TITLE
Adding to typescript-runtime-type-benchmarks repo

### ISSUE THREAD

**Issue by moltar** [grantila/suretype#2]
Hi,

Your project looks very interesting and I'd like to add it to the [typescript-runtime-type-benchmarks](https://github.com/moltar/typescript-runtime-type-benchmarks) repo.

However, I ran into some [issues with the types](https://github.com/moltar/typescript-runtime-type-benchmarks/pull/588).

Was wondering if you could take a look and help resolving it.

Thanks!

**Comment by grantila** [comment]
Great contribution! Added [a PR](https://github.com/moltar/typescript-runtime-type-benchmarks/pull/589) to [your PR](https://github.com/moltar/typescript-runtime-type-benchmarks/pull/588), which makes it green in the pipeline 👍

**Comment by grantila** [comment]
Not sure how you produce your graphs tho, and you might want to add suretype as one of those "outliers", since it's so fast 😊
