### ISSUE TITLE
Prototype Pollution in node-jsonpointer

### ISSUE THREAD

**Issue by Magnielcz** [grantila/suretype#30]
Please upgrade dependency awesome-ajv-errors to version 5.0.0 to avoid this vulnerability.

Prototype Pollution in node-jsonpointer - https://github.com/advisories/GHSA-282f-qqgm-c34q

Will install typeconv@1.2.0, which is a breaking change
node_modules/jsonpointer
  awesome-ajv-errors  <=2.0.0
  Depends on vulnerable versions of jsonpointer
  node_modules/awesome-ajv-errors
    suretype  <=2.4.1
    Depends on vulnerable versions of awesome-ajv-errors
    node_modules/suretype

**Comment by grantila** [comment]
Thanks! This should be fixed in 3.1.0.
